// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: global_def.proto

package ccapi;

public final class GlobalDef {
  private GlobalDef() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code ccapi.ErrCode}
   */
  public enum ErrCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ERR_SUCCESS = 0;</code>
     *
     * <pre>
     *0 成功
     * </pre>
     */
    ERR_SUCCESS(0, 0),
    /**
     * <code>ERR_FAILED = 1;</code>
     *
     * <pre>
     *1 失败
     * </pre>
     */
    ERR_FAILED(1, 1),
    /**
     * <code>ERR_ADDR_ALREADY_EXIST = 2;</code>
     *
     * <pre>
     *2 地址已经存在
     * </pre>
     */
    ERR_ADDR_ALREADY_EXIST(2, 2),
    /**
     * <code>ERR_CONN_TO_DA_NOT_READY = 3;</code>
     *
     * <pre>
     *3 连接没有准备好
     * </pre>
     */
    ERR_CONN_TO_DA_NOT_READY(3, 3),
    /**
     * <code>ERR_INVALID_PUBKEY = 4;</code>
     *
     * <pre>
     *4 非法公钥
     * </pre>
     */
    ERR_INVALID_PUBKEY(4, 4),
    /**
     * <code>ERR_INSUFF_FUNDS = 5;</code>
     *
     * <pre>
     *5 资金不足
     * </pre>
     */
    ERR_INSUFF_FUNDS(5, 5),
    /**
     * <code>ERR_INVALID_AMT = 6;</code>
     *
     * <pre>
     *6 非法帐号
     * </pre>
     */
    ERR_INVALID_AMT(6, 6),
    /**
     * <code>ERR_INVALID_FEE = 7;</code>
     *
     * <pre>
     *7 非法fee
     * </pre>
     */
    ERR_INVALID_FEE(7, 7),
    /**
     * <code>ERR_INVALID_SIGNATURE = 8;</code>
     *
     * <pre>
     *8 非法签名
     * </pre>
     */
    ERR_INVALID_SIGNATURE(8, 8),
    /**
     * <code>ERR_INVALID_ADDR = 9;</code>
     *
     * <pre>
     *9 非法地址
     * </pre>
     */
    ERR_INVALID_ADDR(9, 9),
    /**
     * <code>ERR_INVALID_FROM_ADDR = 10;</code>
     *
     * <pre>
     *10 非法的转出地址
     * </pre>
     */
    ERR_INVALID_FROM_ADDR(10, 10),
    /**
     * <code>ERR_INVALID_TO_ADDR = 11;</code>
     *
     * <pre>
     *11 非法的转入地址
     * </pre>
     */
    ERR_INVALID_TO_ADDR(11, 11),
    /**
     * <code>ERR_NONEXIST_ADDR = 12;</code>
     *
     * <pre>
     *12 地址不存在
     * </pre>
     */
    ERR_NONEXIST_ADDR(12, 12),
    /**
     * <code>ERR_OUT_MAX_AMOUNT = 13;</code>
     *
     * <pre>
     *13 超出最大金额
     * </pre>
     */
    ERR_OUT_MAX_AMOUNT(13, 13),
    /**
     * <code>ERR_BALANCE_ZERO = 14;</code>
     *
     * <pre>
     *14 帐户余额不正常
     * </pre>
     */
    ERR_BALANCE_ZERO(14, 14),
    /**
     * <code>ERR_IS_EXIST = 15;</code>
     *
     * <pre>
     *15 已经存在记录
     * </pre>
     */
    ERR_IS_EXIST(15, 15),
    /**
     * <code>ERR_RECHARGE_EEE_QT_DDD = 16;</code>
     *
     * <pre>
     *16 提币时 ddd不能大于 eee
     * </pre>
     */
    ERR_RECHARGE_EEE_QT_DDD(16, 16),
    /**
     * <code>ERR_PLAY_LIQUIDATE_VERIFY = 17;</code>
     *
     * <pre>
     *17 结算时 校验结算结果失败
     * </pre>
     */
    ERR_PLAY_LIQUIDATE_VERIFY(17, 17),
    /**
     * <code>ERR_DDDADDR_IS_NOT_RULES = 18;</code>
     *
     * <pre>
     *18 DDD地址不符合规则
     * </pre>
     */
    ERR_DDDADDR_IS_NOT_RULES(18, 18),
    ;

    /**
     * <code>ERR_SUCCESS = 0;</code>
     *
     * <pre>
     *0 成功
     * </pre>
     */
    public static final int ERR_SUCCESS_VALUE = 0;
    /**
     * <code>ERR_FAILED = 1;</code>
     *
     * <pre>
     *1 失败
     * </pre>
     */
    public static final int ERR_FAILED_VALUE = 1;
    /**
     * <code>ERR_ADDR_ALREADY_EXIST = 2;</code>
     *
     * <pre>
     *2 地址已经存在
     * </pre>
     */
    public static final int ERR_ADDR_ALREADY_EXIST_VALUE = 2;
    /**
     * <code>ERR_CONN_TO_DA_NOT_READY = 3;</code>
     *
     * <pre>
     *3 连接没有准备好
     * </pre>
     */
    public static final int ERR_CONN_TO_DA_NOT_READY_VALUE = 3;
    /**
     * <code>ERR_INVALID_PUBKEY = 4;</code>
     *
     * <pre>
     *4 非法公钥
     * </pre>
     */
    public static final int ERR_INVALID_PUBKEY_VALUE = 4;
    /**
     * <code>ERR_INSUFF_FUNDS = 5;</code>
     *
     * <pre>
     *5 资金不足
     * </pre>
     */
    public static final int ERR_INSUFF_FUNDS_VALUE = 5;
    /**
     * <code>ERR_INVALID_AMT = 6;</code>
     *
     * <pre>
     *6 非法帐号
     * </pre>
     */
    public static final int ERR_INVALID_AMT_VALUE = 6;
    /**
     * <code>ERR_INVALID_FEE = 7;</code>
     *
     * <pre>
     *7 非法fee
     * </pre>
     */
    public static final int ERR_INVALID_FEE_VALUE = 7;
    /**
     * <code>ERR_INVALID_SIGNATURE = 8;</code>
     *
     * <pre>
     *8 非法签名
     * </pre>
     */
    public static final int ERR_INVALID_SIGNATURE_VALUE = 8;
    /**
     * <code>ERR_INVALID_ADDR = 9;</code>
     *
     * <pre>
     *9 非法地址
     * </pre>
     */
    public static final int ERR_INVALID_ADDR_VALUE = 9;
    /**
     * <code>ERR_INVALID_FROM_ADDR = 10;</code>
     *
     * <pre>
     *10 非法的转出地址
     * </pre>
     */
    public static final int ERR_INVALID_FROM_ADDR_VALUE = 10;
    /**
     * <code>ERR_INVALID_TO_ADDR = 11;</code>
     *
     * <pre>
     *11 非法的转入地址
     * </pre>
     */
    public static final int ERR_INVALID_TO_ADDR_VALUE = 11;
    /**
     * <code>ERR_NONEXIST_ADDR = 12;</code>
     *
     * <pre>
     *12 地址不存在
     * </pre>
     */
    public static final int ERR_NONEXIST_ADDR_VALUE = 12;
    /**
     * <code>ERR_OUT_MAX_AMOUNT = 13;</code>
     *
     * <pre>
     *13 超出最大金额
     * </pre>
     */
    public static final int ERR_OUT_MAX_AMOUNT_VALUE = 13;
    /**
     * <code>ERR_BALANCE_ZERO = 14;</code>
     *
     * <pre>
     *14 帐户余额不正常
     * </pre>
     */
    public static final int ERR_BALANCE_ZERO_VALUE = 14;
    /**
     * <code>ERR_IS_EXIST = 15;</code>
     *
     * <pre>
     *15 已经存在记录
     * </pre>
     */
    public static final int ERR_IS_EXIST_VALUE = 15;
    /**
     * <code>ERR_RECHARGE_EEE_QT_DDD = 16;</code>
     *
     * <pre>
     *16 提币时 ddd不能大于 eee
     * </pre>
     */
    public static final int ERR_RECHARGE_EEE_QT_DDD_VALUE = 16;
    /**
     * <code>ERR_PLAY_LIQUIDATE_VERIFY = 17;</code>
     *
     * <pre>
     *17 结算时 校验结算结果失败
     * </pre>
     */
    public static final int ERR_PLAY_LIQUIDATE_VERIFY_VALUE = 17;
    /**
     * <code>ERR_DDDADDR_IS_NOT_RULES = 18;</code>
     *
     * <pre>
     *18 DDD地址不符合规则
     * </pre>
     */
    public static final int ERR_DDDADDR_IS_NOT_RULES_VALUE = 18;


    public final int getNumber() { return value; }

    public static ErrCode valueOf(int value) {
      switch (value) {
        case 0: return ERR_SUCCESS;
        case 1: return ERR_FAILED;
        case 2: return ERR_ADDR_ALREADY_EXIST;
        case 3: return ERR_CONN_TO_DA_NOT_READY;
        case 4: return ERR_INVALID_PUBKEY;
        case 5: return ERR_INSUFF_FUNDS;
        case 6: return ERR_INVALID_AMT;
        case 7: return ERR_INVALID_FEE;
        case 8: return ERR_INVALID_SIGNATURE;
        case 9: return ERR_INVALID_ADDR;
        case 10: return ERR_INVALID_FROM_ADDR;
        case 11: return ERR_INVALID_TO_ADDR;
        case 12: return ERR_NONEXIST_ADDR;
        case 13: return ERR_OUT_MAX_AMOUNT;
        case 14: return ERR_BALANCE_ZERO;
        case 15: return ERR_IS_EXIST;
        case 16: return ERR_RECHARGE_EEE_QT_DDD;
        case 17: return ERR_PLAY_LIQUIDATE_VERIFY;
        case 18: return ERR_DDDADDR_IS_NOT_RULES;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ErrCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrCode>() {
            public ErrCode findValueByNumber(int number) {
              return ErrCode.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ccapi.GlobalDef.getDescriptor().getEnumTypes().get(0);
    }

    private static final ErrCode[] VALUES = values();

    public static ErrCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ErrCode(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ccapi.ErrCode)
  }

  /**
   * Protobuf enum {@code ccapi.EventCode}
   */
  public enum EventCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EVENT_Type = 0;</code>
     *
     * <pre>
     * </pre>
     */
    EVENT_Type(0, 0),
    /**
     * <code>EVENT_CREATEUSER = 1;</code>
     *
     * <pre>
     *创建用户 da_model.UserEvent
     * </pre>
     */
    EVENT_CREATEUSER(1, 1),
    /**
     * <code>EVENT_RECHARGE = 2;</code>
     *
     * <pre>
     *充值 //da_model.RechargePurchase
     * </pre>
     */
    EVENT_RECHARGE(2, 2),
    /**
     * <code>EVENT_CREATENPC = 3;</code>
     *
     * <pre>
     *创建NPC  da_model.UserEvent
     * </pre>
     */
    EVENT_CREATENPC(3, 3),
    /**
     * <code>EVENT_PlayorTRANSFER = 4;</code>
     *
     * <pre>
     *交易 //da_model.PlayTransferEvt
     * </pre>
     */
    EVENT_PlayorTRANSFER(4, 4),
    /**
     * <code>EVENT_PUSHCONTRACT = 5;</code>
     *
     * <pre>
     *部署劳务合同 da_model.PushContractEvt
     * </pre>
     */
    EVENT_PUSHCONTRACT(5, 5),
    /**
     * <code>EVENT_EMPLOYNPC = 6;</code>
     *
     * <pre>
     *EmployNpc da_model.EmployNpcEvt
     * </pre>
     */
    EVENT_EMPLOYNPC(6, 6),
    /**
     * <code>EVENT_ACTIVETRANSF = 7;</code>
     *
     * <pre>
     *主动交易 da_model.ActiveTransf
     * </pre>
     */
    EVENT_ACTIVETRANSF(7, 7),
    /**
     * <code>EVENT_DISMISS = 8;</code>
     *
     * <pre>
     *解雇npc da_model.DisMissEvt
     * </pre>
     */
    EVENT_DISMISS(8, 8),
    /**
     * <code>EVENT_DISCHARGE = 9;</code>
     *
     * <pre>
     *提币 da_model.DisChargeEvt
     * </pre>
     */
    EVENT_DISCHARGE(9, 9),
    ;

    /**
     * <code>EVENT_Type = 0;</code>
     *
     * <pre>
     * </pre>
     */
    public static final int EVENT_Type_VALUE = 0;
    /**
     * <code>EVENT_CREATEUSER = 1;</code>
     *
     * <pre>
     *创建用户 da_model.UserEvent
     * </pre>
     */
    public static final int EVENT_CREATEUSER_VALUE = 1;
    /**
     * <code>EVENT_RECHARGE = 2;</code>
     *
     * <pre>
     *充值 //da_model.RechargePurchase
     * </pre>
     */
    public static final int EVENT_RECHARGE_VALUE = 2;
    /**
     * <code>EVENT_CREATENPC = 3;</code>
     *
     * <pre>
     *创建NPC  da_model.UserEvent
     * </pre>
     */
    public static final int EVENT_CREATENPC_VALUE = 3;
    /**
     * <code>EVENT_PlayorTRANSFER = 4;</code>
     *
     * <pre>
     *交易 //da_model.PlayTransferEvt
     * </pre>
     */
    public static final int EVENT_PlayorTRANSFER_VALUE = 4;
    /**
     * <code>EVENT_PUSHCONTRACT = 5;</code>
     *
     * <pre>
     *部署劳务合同 da_model.PushContractEvt
     * </pre>
     */
    public static final int EVENT_PUSHCONTRACT_VALUE = 5;
    /**
     * <code>EVENT_EMPLOYNPC = 6;</code>
     *
     * <pre>
     *EmployNpc da_model.EmployNpcEvt
     * </pre>
     */
    public static final int EVENT_EMPLOYNPC_VALUE = 6;
    /**
     * <code>EVENT_ACTIVETRANSF = 7;</code>
     *
     * <pre>
     *主动交易 da_model.ActiveTransf
     * </pre>
     */
    public static final int EVENT_ACTIVETRANSF_VALUE = 7;
    /**
     * <code>EVENT_DISMISS = 8;</code>
     *
     * <pre>
     *解雇npc da_model.DisMissEvt
     * </pre>
     */
    public static final int EVENT_DISMISS_VALUE = 8;
    /**
     * <code>EVENT_DISCHARGE = 9;</code>
     *
     * <pre>
     *提币 da_model.DisChargeEvt
     * </pre>
     */
    public static final int EVENT_DISCHARGE_VALUE = 9;


    public final int getNumber() { return value; }

    public static EventCode valueOf(int value) {
      switch (value) {
        case 0: return EVENT_Type;
        case 1: return EVENT_CREATEUSER;
        case 2: return EVENT_RECHARGE;
        case 3: return EVENT_CREATENPC;
        case 4: return EVENT_PlayorTRANSFER;
        case 5: return EVENT_PUSHCONTRACT;
        case 6: return EVENT_EMPLOYNPC;
        case 7: return EVENT_ACTIVETRANSF;
        case 8: return EVENT_DISMISS;
        case 9: return EVENT_DISCHARGE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EventCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EventCode>() {
            public EventCode findValueByNumber(int number) {
              return EventCode.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ccapi.GlobalDef.getDescriptor().getEnumTypes().get(1);
    }

    private static final EventCode[] VALUES = values();

    public static EventCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private EventCode(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ccapi.EventCode)
  }

  public interface ResHeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 Version = 1;
    /**
     * <code>required int32 Version = 1;</code>
     *
     * <pre>
     * 现在版本默认为 1
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>required int32 Version = 1;</code>
     *
     * <pre>
     * 现在版本默认为 1
     * </pre>
     */
    int getVersion();

    // required .ccapi.ErrCode ErrCode = 2;
    /**
     * <code>required .ccapi.ErrCode ErrCode = 2;</code>
     */
    boolean hasErrCode();
    /**
     * <code>required .ccapi.ErrCode ErrCode = 2;</code>
     */
    ccapi.GlobalDef.ErrCode getErrCode();

    // required string ErrMsg = 3;
    /**
     * <code>required string ErrMsg = 3;</code>
     */
    boolean hasErrMsg();
    /**
     * <code>required string ErrMsg = 3;</code>
     */
    java.lang.String getErrMsg();
    /**
     * <code>required string ErrMsg = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrMsgBytes();

    // required string ReqId = 4;
    /**
     * <code>required string ReqId = 4;</code>
     */
    boolean hasReqId();
    /**
     * <code>required string ReqId = 4;</code>
     */
    java.lang.String getReqId();
    /**
     * <code>required string ReqId = 4;</code>
     */
    com.google.protobuf.ByteString
        getReqIdBytes();
  }
  /**
   * Protobuf type {@code ccapi.ResHeader}
   */
  public static final class ResHeader extends
      com.google.protobuf.GeneratedMessage
      implements ResHeaderOrBuilder {
    // Use ResHeader.newBuilder() to construct.
    private ResHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResHeader defaultInstance;
    public static ResHeader getDefaultInstance() {
      return defaultInstance;
    }

    public ResHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              ccapi.GlobalDef.ErrCode value = ccapi.GlobalDef.ErrCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                errCode_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              errMsg_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              reqId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ccapi.GlobalDef.internal_static_ccapi_ResHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ccapi.GlobalDef.internal_static_ccapi_ResHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ccapi.GlobalDef.ResHeader.class, ccapi.GlobalDef.ResHeader.Builder.class);
    }

    public static com.google.protobuf.Parser<ResHeader> PARSER =
        new com.google.protobuf.AbstractParser<ResHeader>() {
      public ResHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResHeader(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResHeader> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 Version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 Version = 1;</code>
     *
     * <pre>
     * 现在版本默认为 1
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 Version = 1;</code>
     *
     * <pre>
     * 现在版本默认为 1
     * </pre>
     */
    public int getVersion() {
      return version_;
    }

    // required .ccapi.ErrCode ErrCode = 2;
    public static final int ERRCODE_FIELD_NUMBER = 2;
    private ccapi.GlobalDef.ErrCode errCode_;
    /**
     * <code>required .ccapi.ErrCode ErrCode = 2;</code>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .ccapi.ErrCode ErrCode = 2;</code>
     */
    public ccapi.GlobalDef.ErrCode getErrCode() {
      return errCode_;
    }

    // required string ErrMsg = 3;
    public static final int ERRMSG_FIELD_NUMBER = 3;
    private java.lang.Object errMsg_;
    /**
     * <code>required string ErrMsg = 3;</code>
     */
    public boolean hasErrMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string ErrMsg = 3;</code>
     */
    public java.lang.String getErrMsg() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ErrMsg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string ReqId = 4;
    public static final int REQID_FIELD_NUMBER = 4;
    private java.lang.Object reqId_;
    /**
     * <code>required string ReqId = 4;</code>
     */
    public boolean hasReqId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string ReqId = 4;</code>
     */
    public java.lang.String getReqId() {
      java.lang.Object ref = reqId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reqId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ReqId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getReqIdBytes() {
      java.lang.Object ref = reqId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      version_ = 0;
      errCode_ = ccapi.GlobalDef.ErrCode.ERR_SUCCESS;
      errMsg_ = "";
      reqId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasErrCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasErrMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReqId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, errCode_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getErrMsgBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getReqIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, errCode_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getErrMsgBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getReqIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ccapi.GlobalDef.ResHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ccapi.GlobalDef.ResHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ccapi.GlobalDef.ResHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ccapi.GlobalDef.ResHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ccapi.GlobalDef.ResHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ccapi.GlobalDef.ResHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ccapi.GlobalDef.ResHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ccapi.GlobalDef.ResHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ccapi.GlobalDef.ResHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ccapi.GlobalDef.ResHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ccapi.GlobalDef.ResHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ccapi.ResHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ccapi.GlobalDef.ResHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ccapi.GlobalDef.internal_static_ccapi_ResHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ccapi.GlobalDef.internal_static_ccapi_ResHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ccapi.GlobalDef.ResHeader.class, ccapi.GlobalDef.ResHeader.Builder.class);
      }

      // Construct using ccapi.GlobalDef.ResHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        errCode_ = ccapi.GlobalDef.ErrCode.ERR_SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000002);
        errMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        reqId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ccapi.GlobalDef.internal_static_ccapi_ResHeader_descriptor;
      }

      public ccapi.GlobalDef.ResHeader getDefaultInstanceForType() {
        return ccapi.GlobalDef.ResHeader.getDefaultInstance();
      }

      public ccapi.GlobalDef.ResHeader build() {
        ccapi.GlobalDef.ResHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ccapi.GlobalDef.ResHeader buildPartial() {
        ccapi.GlobalDef.ResHeader result = new ccapi.GlobalDef.ResHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errCode_ = errCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errMsg_ = errMsg_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.reqId_ = reqId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ccapi.GlobalDef.ResHeader) {
          return mergeFrom((ccapi.GlobalDef.ResHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ccapi.GlobalDef.ResHeader other) {
        if (other == ccapi.GlobalDef.ResHeader.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasErrMsg()) {
          bitField0_ |= 0x00000004;
          errMsg_ = other.errMsg_;
          onChanged();
        }
        if (other.hasReqId()) {
          bitField0_ |= 0x00000008;
          reqId_ = other.reqId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasErrCode()) {
          
          return false;
        }
        if (!hasErrMsg()) {
          
          return false;
        }
        if (!hasReqId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ccapi.GlobalDef.ResHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ccapi.GlobalDef.ResHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 Version = 1;
      private int version_ ;
      /**
       * <code>required int32 Version = 1;</code>
       *
       * <pre>
       * 现在版本默认为 1
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 Version = 1;</code>
       *
       * <pre>
       * 现在版本默认为 1
       * </pre>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required int32 Version = 1;</code>
       *
       * <pre>
       * 现在版本默认为 1
       * </pre>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 Version = 1;</code>
       *
       * <pre>
       * 现在版本默认为 1
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      // required .ccapi.ErrCode ErrCode = 2;
      private ccapi.GlobalDef.ErrCode errCode_ = ccapi.GlobalDef.ErrCode.ERR_SUCCESS;
      /**
       * <code>required .ccapi.ErrCode ErrCode = 2;</code>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .ccapi.ErrCode ErrCode = 2;</code>
       */
      public ccapi.GlobalDef.ErrCode getErrCode() {
        return errCode_;
      }
      /**
       * <code>required .ccapi.ErrCode ErrCode = 2;</code>
       */
      public Builder setErrCode(ccapi.GlobalDef.ErrCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .ccapi.ErrCode ErrCode = 2;</code>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errCode_ = ccapi.GlobalDef.ErrCode.ERR_SUCCESS;
        onChanged();
        return this;
      }

      // required string ErrMsg = 3;
      private java.lang.Object errMsg_ = "";
      /**
       * <code>required string ErrMsg = 3;</code>
       */
      public boolean hasErrMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string ErrMsg = 3;</code>
       */
      public java.lang.String getErrMsg() {
        java.lang.Object ref = errMsg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          errMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ErrMsg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrMsgBytes() {
        java.lang.Object ref = errMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ErrMsg = 3;</code>
       */
      public Builder setErrMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        errMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ErrMsg = 3;</code>
       */
      public Builder clearErrMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errMsg_ = getDefaultInstance().getErrMsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string ErrMsg = 3;</code>
       */
      public Builder setErrMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        errMsg_ = value;
        onChanged();
        return this;
      }

      // required string ReqId = 4;
      private java.lang.Object reqId_ = "";
      /**
       * <code>required string ReqId = 4;</code>
       */
      public boolean hasReqId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string ReqId = 4;</code>
       */
      public java.lang.String getReqId() {
        java.lang.Object ref = reqId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          reqId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ReqId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getReqIdBytes() {
        java.lang.Object ref = reqId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ReqId = 4;</code>
       */
      public Builder setReqId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        reqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ReqId = 4;</code>
       */
      public Builder clearReqId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        reqId_ = getDefaultInstance().getReqId();
        onChanged();
        return this;
      }
      /**
       * <code>required string ReqId = 4;</code>
       */
      public Builder setReqIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        reqId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ccapi.ResHeader)
    }

    static {
      defaultInstance = new ResHeader(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ccapi.ResHeader)
  }

  public interface ReqHeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 Version = 1;
    /**
     * <code>required int32 Version = 1;</code>
     *
     * <pre>
     * 现在版本默认为 1
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>required int32 Version = 1;</code>
     *
     * <pre>
     * 现在版本默认为 1
     * </pre>
     */
    int getVersion();

    // required string ReqId = 4;
    /**
     * <code>required string ReqId = 4;</code>
     *
     * <pre>
     * city 端所有的请求加入唯一的请求id
     * </pre>
     */
    boolean hasReqId();
    /**
     * <code>required string ReqId = 4;</code>
     *
     * <pre>
     * city 端所有的请求加入唯一的请求id
     * </pre>
     */
    java.lang.String getReqId();
    /**
     * <code>required string ReqId = 4;</code>
     *
     * <pre>
     * city 端所有的请求加入唯一的请求id
     * </pre>
     */
    com.google.protobuf.ByteString
        getReqIdBytes();
  }
  /**
   * Protobuf type {@code ccapi.ReqHeader}
   */
  public static final class ReqHeader extends
      com.google.protobuf.GeneratedMessage
      implements ReqHeaderOrBuilder {
    // Use ReqHeader.newBuilder() to construct.
    private ReqHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqHeader defaultInstance;
    public static ReqHeader getDefaultInstance() {
      return defaultInstance;
    }

    public ReqHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000002;
              reqId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ccapi.GlobalDef.internal_static_ccapi_ReqHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ccapi.GlobalDef.internal_static_ccapi_ReqHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ccapi.GlobalDef.ReqHeader.class, ccapi.GlobalDef.ReqHeader.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqHeader> PARSER =
        new com.google.protobuf.AbstractParser<ReqHeader>() {
      public ReqHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqHeader(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqHeader> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 Version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 Version = 1;</code>
     *
     * <pre>
     * 现在版本默认为 1
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 Version = 1;</code>
     *
     * <pre>
     * 现在版本默认为 1
     * </pre>
     */
    public int getVersion() {
      return version_;
    }

    // required string ReqId = 4;
    public static final int REQID_FIELD_NUMBER = 4;
    private java.lang.Object reqId_;
    /**
     * <code>required string ReqId = 4;</code>
     *
     * <pre>
     * city 端所有的请求加入唯一的请求id
     * </pre>
     */
    public boolean hasReqId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string ReqId = 4;</code>
     *
     * <pre>
     * city 端所有的请求加入唯一的请求id
     * </pre>
     */
    public java.lang.String getReqId() {
      java.lang.Object ref = reqId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reqId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ReqId = 4;</code>
     *
     * <pre>
     * city 端所有的请求加入唯一的请求id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getReqIdBytes() {
      java.lang.Object ref = reqId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      version_ = 0;
      reqId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReqId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(4, getReqIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getReqIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ccapi.GlobalDef.ReqHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ccapi.GlobalDef.ReqHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ccapi.GlobalDef.ReqHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ccapi.GlobalDef.ReqHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ccapi.GlobalDef.ReqHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ccapi.GlobalDef.ReqHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ccapi.GlobalDef.ReqHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ccapi.GlobalDef.ReqHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ccapi.GlobalDef.ReqHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ccapi.GlobalDef.ReqHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ccapi.GlobalDef.ReqHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ccapi.ReqHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ccapi.GlobalDef.ReqHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ccapi.GlobalDef.internal_static_ccapi_ReqHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ccapi.GlobalDef.internal_static_ccapi_ReqHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ccapi.GlobalDef.ReqHeader.class, ccapi.GlobalDef.ReqHeader.Builder.class);
      }

      // Construct using ccapi.GlobalDef.ReqHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        reqId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ccapi.GlobalDef.internal_static_ccapi_ReqHeader_descriptor;
      }

      public ccapi.GlobalDef.ReqHeader getDefaultInstanceForType() {
        return ccapi.GlobalDef.ReqHeader.getDefaultInstance();
      }

      public ccapi.GlobalDef.ReqHeader build() {
        ccapi.GlobalDef.ReqHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ccapi.GlobalDef.ReqHeader buildPartial() {
        ccapi.GlobalDef.ReqHeader result = new ccapi.GlobalDef.ReqHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.reqId_ = reqId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ccapi.GlobalDef.ReqHeader) {
          return mergeFrom((ccapi.GlobalDef.ReqHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ccapi.GlobalDef.ReqHeader other) {
        if (other == ccapi.GlobalDef.ReqHeader.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasReqId()) {
          bitField0_ |= 0x00000002;
          reqId_ = other.reqId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasReqId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ccapi.GlobalDef.ReqHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ccapi.GlobalDef.ReqHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 Version = 1;
      private int version_ ;
      /**
       * <code>required int32 Version = 1;</code>
       *
       * <pre>
       * 现在版本默认为 1
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 Version = 1;</code>
       *
       * <pre>
       * 现在版本默认为 1
       * </pre>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required int32 Version = 1;</code>
       *
       * <pre>
       * 现在版本默认为 1
       * </pre>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 Version = 1;</code>
       *
       * <pre>
       * 现在版本默认为 1
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      // required string ReqId = 4;
      private java.lang.Object reqId_ = "";
      /**
       * <code>required string ReqId = 4;</code>
       *
       * <pre>
       * city 端所有的请求加入唯一的请求id
       * </pre>
       */
      public boolean hasReqId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string ReqId = 4;</code>
       *
       * <pre>
       * city 端所有的请求加入唯一的请求id
       * </pre>
       */
      public java.lang.String getReqId() {
        java.lang.Object ref = reqId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          reqId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ReqId = 4;</code>
       *
       * <pre>
       * city 端所有的请求加入唯一的请求id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getReqIdBytes() {
        java.lang.Object ref = reqId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ReqId = 4;</code>
       *
       * <pre>
       * city 端所有的请求加入唯一的请求id
       * </pre>
       */
      public Builder setReqId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        reqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ReqId = 4;</code>
       *
       * <pre>
       * city 端所有的请求加入唯一的请求id
       * </pre>
       */
      public Builder clearReqId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reqId_ = getDefaultInstance().getReqId();
        onChanged();
        return this;
      }
      /**
       * <code>required string ReqId = 4;</code>
       *
       * <pre>
       * city 端所有的请求加入唯一的请求id
       * </pre>
       */
      public Builder setReqIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        reqId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ccapi.ReqHeader)
    }

    static {
      defaultInstance = new ReqHeader(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ccapi.ReqHeader)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ccapi_ResHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ccapi_ResHeader_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ccapi_ReqHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ccapi_ReqHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020global_def.proto\022\005ccapi\"\\\n\tResHeader\022\017" +
      "\n\007Version\030\001 \002(\005\022\037\n\007ErrCode\030\002 \002(\0162\016.ccapi" +
      ".ErrCode\022\016\n\006ErrMsg\030\003 \002(\t\022\r\n\005ReqId\030\004 \002(\t\"" +
      "+\n\tReqHeader\022\017\n\007Version\030\001 \002(\005\022\r\n\005ReqId\030\004" +
      " \002(\t*\322\003\n\007ErrCode\022\017\n\013ERR_SUCCESS\020\000\022\016\n\nERR" +
      "_FAILED\020\001\022\032\n\026ERR_ADDR_ALREADY_EXIST\020\002\022\034\n" +
      "\030ERR_CONN_TO_DA_NOT_READY\020\003\022\026\n\022ERR_INVAL" +
      "ID_PUBKEY\020\004\022\024\n\020ERR_INSUFF_FUNDS\020\005\022\023\n\017ERR" +
      "_INVALID_AMT\020\006\022\023\n\017ERR_INVALID_FEE\020\007\022\031\n\025E" +
      "RR_INVALID_SIGNATURE\020\010\022\024\n\020ERR_INVALID_AD",
      "DR\020\t\022\031\n\025ERR_INVALID_FROM_ADDR\020\n\022\027\n\023ERR_I" +
      "NVALID_TO_ADDR\020\013\022\025\n\021ERR_NONEXIST_ADDR\020\014\022" +
      "\026\n\022ERR_OUT_MAX_AMOUNT\020\r\022\024\n\020ERR_BALANCE_Z" +
      "ERO\020\016\022\020\n\014ERR_IS_EXIST\020\017\022\033\n\027ERR_RECHARGE_" +
      "EEE_QT_DDD\020\020\022\035\n\031ERR_PLAY_LIQUIDATE_VERIF" +
      "Y\020\021\022\034\n\030ERR_DDDADDR_IS_NOT_RULES\020\022*\341\001\n\tEv" +
      "entCode\022\016\n\nEVENT_Type\020\000\022\024\n\020EVENT_CREATEU" +
      "SER\020\001\022\022\n\016EVENT_RECHARGE\020\002\022\023\n\017EVENT_CREAT" +
      "ENPC\020\003\022\030\n\024EVENT_PlayorTRANSFER\020\004\022\026\n\022EVEN" +
      "T_PUSHCONTRACT\020\005\022\023\n\017EVENT_EMPLOYNPC\020\006\022\026\n",
      "\022EVENT_ACTIVETRANSF\020\007\022\021\n\rEVENT_DISMISS\020\010" +
      "\022\023\n\017EVENT_DISCHARGE\020\tB9Z7github.com/scry" +
      "info/citychain-s/ccapi/grpc/go_out/ccapi"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ccapi_ResHeader_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ccapi_ResHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ccapi_ResHeader_descriptor,
              new java.lang.String[] { "Version", "ErrCode", "ErrMsg", "ReqId", });
          internal_static_ccapi_ReqHeader_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ccapi_ReqHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ccapi_ReqHeader_descriptor,
              new java.lang.String[] { "Version", "ReqId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
