// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gaCode.proto

package gacode;

public final class GaCode {
  private GaCode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code gacode.OpCode}
   */
  public enum OpCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>error = 0;</code>
     */
    error(0),
    /**
     * <code>login = 1;</code>
     */
    login(1),
    /**
     * <code>serverInfo = 2;</code>
     */
    serverInfo(2),
    /**
     * <code>stateReport = 3;</code>
     */
    stateReport(3),
    /**
     * <pre>
     * ack of AccountToGameOpCode::validate_info 
     * </pre>
     *
     * <code>validateAck = 4;</code>
     */
    validateAck(4),
    /**
     * <code>validateInfo = 11;</code>
     */
    validateInfo(11),
    /**
     * <code>chargeInform = 12;</code>
     */
    chargeInform(12),
    /**
     * <code>sendMail = 13;</code>
     */
    sendMail(13),
    /**
     * <code>banChat = 14;</code>
     */
    banChat(14),
    /**
     * <code>announcement = 15;</code>
     */
    announcement(15),
    /**
     * <code>kickAllRole = 16;</code>
     */
    kickAllRole(16),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>error = 0;</code>
     */
    public static final int error_VALUE = 0;
    /**
     * <code>login = 1;</code>
     */
    public static final int login_VALUE = 1;
    /**
     * <code>serverInfo = 2;</code>
     */
    public static final int serverInfo_VALUE = 2;
    /**
     * <code>stateReport = 3;</code>
     */
    public static final int stateReport_VALUE = 3;
    /**
     * <pre>
     * ack of AccountToGameOpCode::validate_info 
     * </pre>
     *
     * <code>validateAck = 4;</code>
     */
    public static final int validateAck_VALUE = 4;
    /**
     * <code>validateInfo = 11;</code>
     */
    public static final int validateInfo_VALUE = 11;
    /**
     * <code>chargeInform = 12;</code>
     */
    public static final int chargeInform_VALUE = 12;
    /**
     * <code>sendMail = 13;</code>
     */
    public static final int sendMail_VALUE = 13;
    /**
     * <code>banChat = 14;</code>
     */
    public static final int banChat_VALUE = 14;
    /**
     * <code>announcement = 15;</code>
     */
    public static final int announcement_VALUE = 15;
    /**
     * <code>kickAllRole = 16;</code>
     */
    public static final int kickAllRole_VALUE = 16;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OpCode valueOf(int value) {
      return forNumber(value);
    }

    public static OpCode forNumber(int value) {
      switch (value) {
        case 0: return error;
        case 1: return login;
        case 2: return serverInfo;
        case 3: return stateReport;
        case 4: return validateAck;
        case 11: return validateInfo;
        case 12: return chargeInform;
        case 13: return sendMail;
        case 14: return banChat;
        case 15: return announcement;
        case 16: return kickAllRole;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OpCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OpCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OpCode>() {
            public OpCode findValueByNumber(int number) {
              return OpCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return gacode.GaCode.getDescriptor().getEnumTypes().get(0);
    }

    private static final OpCode[] VALUES = values();

    public static OpCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OpCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:gacode.OpCode)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014gaCode.proto\022\006gacode*\262\001\n\006OpCode\022\t\n\005err" +
      "or\020\000\022\t\n\005login\020\001\022\016\n\nserverInfo\020\002\022\017\n\013state" +
      "Report\020\003\022\017\n\013validateAck\020\004\022\020\n\014validateInf" +
      "o\020\013\022\020\n\014chargeInform\020\014\022\014\n\010sendMail\020\r\022\013\n\007b" +
      "anChat\020\016\022\020\n\014announcement\020\017\022\017\n\013kickAllRol" +
      "e\020\020b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
