// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gaCode.proto

package gacode;

public final class GaCode {
  private GaCode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code gacode.OpCode}
   */
  public enum OpCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>login = 1;</code>
     */
    login(0, 1),
    /**
     * <code>serverInfo = 2;</code>
     */
    serverInfo(1, 2),
    /**
     * <code>stateReport = 3;</code>
     */
    stateReport(2, 3),
    /**
     * <code>validateAck = 4;</code>
     *
     * <pre>
     * ack of AccountToGameOpCode::validate_info 
     * </pre>
     */
    validateAck(3, 4),
    /**
     * <code>validateInfo = 11;</code>
     */
    validateInfo(4, 11),
    /**
     * <code>chargeInform = 12;</code>
     */
    chargeInform(5, 12),
    /**
     * <code>sendMail = 13;</code>
     */
    sendMail(6, 13),
    /**
     * <code>banChat = 14;</code>
     */
    banChat(7, 14),
    /**
     * <code>announcement = 15;</code>
     */
    announcement(8, 15),
    /**
     * <code>kickAllRole = 16;</code>
     */
    kickAllRole(9, 16),
    ;

    /**
     * <code>login = 1;</code>
     */
    public static final int login_VALUE = 1;
    /**
     * <code>serverInfo = 2;</code>
     */
    public static final int serverInfo_VALUE = 2;
    /**
     * <code>stateReport = 3;</code>
     */
    public static final int stateReport_VALUE = 3;
    /**
     * <code>validateAck = 4;</code>
     *
     * <pre>
     * ack of AccountToGameOpCode::validate_info 
     * </pre>
     */
    public static final int validateAck_VALUE = 4;
    /**
     * <code>validateInfo = 11;</code>
     */
    public static final int validateInfo_VALUE = 11;
    /**
     * <code>chargeInform = 12;</code>
     */
    public static final int chargeInform_VALUE = 12;
    /**
     * <code>sendMail = 13;</code>
     */
    public static final int sendMail_VALUE = 13;
    /**
     * <code>banChat = 14;</code>
     */
    public static final int banChat_VALUE = 14;
    /**
     * <code>announcement = 15;</code>
     */
    public static final int announcement_VALUE = 15;
    /**
     * <code>kickAllRole = 16;</code>
     */
    public static final int kickAllRole_VALUE = 16;


    public final int getNumber() { return value; }

    public static OpCode valueOf(int value) {
      switch (value) {
        case 1: return login;
        case 2: return serverInfo;
        case 3: return stateReport;
        case 4: return validateAck;
        case 11: return validateInfo;
        case 12: return chargeInform;
        case 13: return sendMail;
        case 14: return banChat;
        case 15: return announcement;
        case 16: return kickAllRole;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OpCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<OpCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OpCode>() {
            public OpCode findValueByNumber(int number) {
              return OpCode.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return gacode.GaCode.getDescriptor().getEnumTypes().get(0);
    }

    private static final OpCode[] VALUES = values();

    public static OpCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private OpCode(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:gacode.OpCode)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014gaCode.proto\022\006gacode*\247\001\n\006OpCode\022\t\n\005log" +
      "in\020\001\022\016\n\nserverInfo\020\002\022\017\n\013stateReport\020\003\022\017\n" +
      "\013validateAck\020\004\022\020\n\014validateInfo\020\013\022\020\n\014char" +
      "geInform\020\014\022\014\n\010sendMail\020\r\022\013\n\007banChat\020\016\022\020\n" +
      "\014announcement\020\017\022\017\n\013kickAllRole\020\020"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
