// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: asCode.proto

package ascode;

public final class AsCode {
  private AsCode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code ascode.OpCode}
   */
  public enum OpCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>login = 1000;</code>
     *
     * <pre>
     *c
     * </pre>
     */
    login(0, 1000),
    /**
     * <code>chooseGameServer = 1001;</code>
     *
     * <pre>
     *c
     * </pre>
     */
    chooseGameServer(1, 1001),
    /**
     * <code>getServerList = 1002;</code>
     *
     * <pre>
     *c
     * </pre>
     */
    getServerList(2, 1002),
    ;

    /**
     * <code>login = 1000;</code>
     *
     * <pre>
     *c
     * </pre>
     */
    public static final int login_VALUE = 1000;
    /**
     * <code>chooseGameServer = 1001;</code>
     *
     * <pre>
     *c
     * </pre>
     */
    public static final int chooseGameServer_VALUE = 1001;
    /**
     * <code>getServerList = 1002;</code>
     *
     * <pre>
     *c
     * </pre>
     */
    public static final int getServerList_VALUE = 1002;


    public final int getNumber() { return value; }

    public static OpCode valueOf(int value) {
      switch (value) {
        case 1000: return login;
        case 1001: return chooseGameServer;
        case 1002: return getServerList;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OpCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<OpCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OpCode>() {
            public OpCode findValueByNumber(int number) {
              return OpCode.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ascode.AsCode.getDescriptor().getEnumTypes().get(0);
    }

    private static final OpCode[] VALUES = values();

    public static OpCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private OpCode(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ascode.OpCode)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014asCode.proto\022\006ascode*?\n\006OpCode\022\n\n\005logi" +
      "n\020\350\007\022\025\n\020chooseGameServer\020\351\007\022\022\n\rgetServer" +
      "List\020\352\007"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
