// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: city.proto

package cityapi;

public final class City {
  private City() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RechargeResultResOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .ccapi.ResHeader ResHeader = 1;
    /**
     * <code>required .ccapi.ResHeader ResHeader = 1;</code>
     */
    boolean hasResHeader();
    /**
     * <code>required .ccapi.ResHeader ResHeader = 1;</code>
     */
    ccapi.GlobalDef.ResHeader getResHeader();
    /**
     * <code>required .ccapi.ResHeader ResHeader = 1;</code>
     */
    ccapi.GlobalDef.ResHeaderOrBuilder getResHeaderOrBuilder();
  }
  /**
   * Protobuf type {@code cityapi.RechargeResultRes}
   */
  public static final class RechargeResultRes extends
      com.google.protobuf.GeneratedMessage
      implements RechargeResultResOrBuilder {
    // Use RechargeResultRes.newBuilder() to construct.
    private RechargeResultRes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RechargeResultRes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RechargeResultRes defaultInstance;
    public static RechargeResultRes getDefaultInstance() {
      return defaultInstance;
    }

    public RechargeResultRes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RechargeResultRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ccapi.GlobalDef.ResHeader.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = resHeader_.toBuilder();
              }
              resHeader_ = input.readMessage(ccapi.GlobalDef.ResHeader.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(resHeader_);
                resHeader_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cityapi.City.internal_static_cityapi_RechargeResultRes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cityapi.City.internal_static_cityapi_RechargeResultRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cityapi.City.RechargeResultRes.class, cityapi.City.RechargeResultRes.Builder.class);
    }

    public static com.google.protobuf.Parser<RechargeResultRes> PARSER =
        new com.google.protobuf.AbstractParser<RechargeResultRes>() {
      public RechargeResultRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RechargeResultRes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RechargeResultRes> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .ccapi.ResHeader ResHeader = 1;
    public static final int RESHEADER_FIELD_NUMBER = 1;
    private ccapi.GlobalDef.ResHeader resHeader_;
    /**
     * <code>required .ccapi.ResHeader ResHeader = 1;</code>
     */
    public boolean hasResHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ccapi.ResHeader ResHeader = 1;</code>
     */
    public ccapi.GlobalDef.ResHeader getResHeader() {
      return resHeader_;
    }
    /**
     * <code>required .ccapi.ResHeader ResHeader = 1;</code>
     */
    public ccapi.GlobalDef.ResHeaderOrBuilder getResHeaderOrBuilder() {
      return resHeader_;
    }

    private void initFields() {
      resHeader_ = ccapi.GlobalDef.ResHeader.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getResHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, resHeader_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, resHeader_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cityapi.City.RechargeResultRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cityapi.City.RechargeResultRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cityapi.City.RechargeResultRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cityapi.City.RechargeResultRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cityapi.City.RechargeResultRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cityapi.City.RechargeResultRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cityapi.City.RechargeResultRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cityapi.City.RechargeResultRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cityapi.City.RechargeResultRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cityapi.City.RechargeResultRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cityapi.City.RechargeResultRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cityapi.RechargeResultRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cityapi.City.RechargeResultResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cityapi.City.internal_static_cityapi_RechargeResultRes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cityapi.City.internal_static_cityapi_RechargeResultRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cityapi.City.RechargeResultRes.class, cityapi.City.RechargeResultRes.Builder.class);
      }

      // Construct using cityapi.City.RechargeResultRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getResHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (resHeaderBuilder_ == null) {
          resHeader_ = ccapi.GlobalDef.ResHeader.getDefaultInstance();
        } else {
          resHeaderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cityapi.City.internal_static_cityapi_RechargeResultRes_descriptor;
      }

      public cityapi.City.RechargeResultRes getDefaultInstanceForType() {
        return cityapi.City.RechargeResultRes.getDefaultInstance();
      }

      public cityapi.City.RechargeResultRes build() {
        cityapi.City.RechargeResultRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cityapi.City.RechargeResultRes buildPartial() {
        cityapi.City.RechargeResultRes result = new cityapi.City.RechargeResultRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (resHeaderBuilder_ == null) {
          result.resHeader_ = resHeader_;
        } else {
          result.resHeader_ = resHeaderBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cityapi.City.RechargeResultRes) {
          return mergeFrom((cityapi.City.RechargeResultRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cityapi.City.RechargeResultRes other) {
        if (other == cityapi.City.RechargeResultRes.getDefaultInstance()) return this;
        if (other.hasResHeader()) {
          mergeResHeader(other.getResHeader());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResHeader()) {
          
          return false;
        }
        if (!getResHeader().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cityapi.City.RechargeResultRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cityapi.City.RechargeResultRes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .ccapi.ResHeader ResHeader = 1;
      private ccapi.GlobalDef.ResHeader resHeader_ = ccapi.GlobalDef.ResHeader.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ccapi.GlobalDef.ResHeader, ccapi.GlobalDef.ResHeader.Builder, ccapi.GlobalDef.ResHeaderOrBuilder> resHeaderBuilder_;
      /**
       * <code>required .ccapi.ResHeader ResHeader = 1;</code>
       */
      public boolean hasResHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .ccapi.ResHeader ResHeader = 1;</code>
       */
      public ccapi.GlobalDef.ResHeader getResHeader() {
        if (resHeaderBuilder_ == null) {
          return resHeader_;
        } else {
          return resHeaderBuilder_.getMessage();
        }
      }
      /**
       * <code>required .ccapi.ResHeader ResHeader = 1;</code>
       */
      public Builder setResHeader(ccapi.GlobalDef.ResHeader value) {
        if (resHeaderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          resHeader_ = value;
          onChanged();
        } else {
          resHeaderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ccapi.ResHeader ResHeader = 1;</code>
       */
      public Builder setResHeader(
          ccapi.GlobalDef.ResHeader.Builder builderForValue) {
        if (resHeaderBuilder_ == null) {
          resHeader_ = builderForValue.build();
          onChanged();
        } else {
          resHeaderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ccapi.ResHeader ResHeader = 1;</code>
       */
      public Builder mergeResHeader(ccapi.GlobalDef.ResHeader value) {
        if (resHeaderBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              resHeader_ != ccapi.GlobalDef.ResHeader.getDefaultInstance()) {
            resHeader_ =
              ccapi.GlobalDef.ResHeader.newBuilder(resHeader_).mergeFrom(value).buildPartial();
          } else {
            resHeader_ = value;
          }
          onChanged();
        } else {
          resHeaderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ccapi.ResHeader ResHeader = 1;</code>
       */
      public Builder clearResHeader() {
        if (resHeaderBuilder_ == null) {
          resHeader_ = ccapi.GlobalDef.ResHeader.getDefaultInstance();
          onChanged();
        } else {
          resHeaderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .ccapi.ResHeader ResHeader = 1;</code>
       */
      public ccapi.GlobalDef.ResHeader.Builder getResHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getResHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .ccapi.ResHeader ResHeader = 1;</code>
       */
      public ccapi.GlobalDef.ResHeaderOrBuilder getResHeaderOrBuilder() {
        if (resHeaderBuilder_ != null) {
          return resHeaderBuilder_.getMessageOrBuilder();
        } else {
          return resHeader_;
        }
      }
      /**
       * <code>required .ccapi.ResHeader ResHeader = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ccapi.GlobalDef.ResHeader, ccapi.GlobalDef.ResHeader.Builder, ccapi.GlobalDef.ResHeaderOrBuilder> 
          getResHeaderFieldBuilder() {
        if (resHeaderBuilder_ == null) {
          resHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ccapi.GlobalDef.ResHeader, ccapi.GlobalDef.ResHeader.Builder, ccapi.GlobalDef.ResHeaderOrBuilder>(
                  resHeader_,
                  getParentForChildren(),
                  isClean());
          resHeader_ = null;
        }
        return resHeaderBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:cityapi.RechargeResultRes)
    }

    static {
      defaultInstance = new RechargeResultRes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cityapi.RechargeResultRes)
  }

  public interface RechargeResultReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .ccapi.ReqHeader ReqHeader = 1;
    /**
     * <code>required .ccapi.ReqHeader ReqHeader = 1;</code>
     */
    boolean hasReqHeader();
    /**
     * <code>required .ccapi.ReqHeader ReqHeader = 1;</code>
     */
    ccapi.GlobalDef.ReqHeader getReqHeader();
    /**
     * <code>required .ccapi.ReqHeader ReqHeader = 1;</code>
     */
    ccapi.GlobalDef.ReqHeaderOrBuilder getReqHeaderOrBuilder();

    // required .ccapi.ErrCode ErrCode = 2;
    /**
     * <code>required .ccapi.ErrCode ErrCode = 2;</code>
     */
    boolean hasErrCode();
    /**
     * <code>required .ccapi.ErrCode ErrCode = 2;</code>
     */
    ccapi.GlobalDef.ErrCode getErrCode();

    // required string ErrMsg = 3;
    /**
     * <code>required string ErrMsg = 3;</code>
     */
    boolean hasErrMsg();
    /**
     * <code>required string ErrMsg = 3;</code>
     */
    java.lang.String getErrMsg();
    /**
     * <code>required string ErrMsg = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrMsgBytes();

    // required string CityPurchaseId = 4;
    /**
     * <code>required string CityPurchaseId = 4;</code>
     */
    boolean hasCityPurchaseId();
    /**
     * <code>required string CityPurchaseId = 4;</code>
     */
    java.lang.String getCityPurchaseId();
    /**
     * <code>required string CityPurchaseId = 4;</code>
     */
    com.google.protobuf.ByteString
        getCityPurchaseIdBytes();

    // required string CccTokenAmount = 5;
    /**
     * <code>required string CccTokenAmount = 5;</code>
     *
     * <pre>
     *带小数点 精度4 、ddd-&gt;ccc 1：1
     * </pre>
     */
    boolean hasCccTokenAmount();
    /**
     * <code>required string CccTokenAmount = 5;</code>
     *
     * <pre>
     *带小数点 精度4 、ddd-&gt;ccc 1：1
     * </pre>
     */
    java.lang.String getCccTokenAmount();
    /**
     * <code>required string CccTokenAmount = 5;</code>
     *
     * <pre>
     *带小数点 精度4 、ddd-&gt;ccc 1：1
     * </pre>
     */
    com.google.protobuf.ByteString
        getCccTokenAmountBytes();

    // required string LastBlockId = 6;
    /**
     * <code>required string LastBlockId = 6;</code>
     */
    boolean hasLastBlockId();
    /**
     * <code>required string LastBlockId = 6;</code>
     */
    java.lang.String getLastBlockId();
    /**
     * <code>required string LastBlockId = 6;</code>
     */
    com.google.protobuf.ByteString
        getLastBlockIdBytes();
  }
  /**
   * Protobuf type {@code cityapi.RechargeResultReq}
   */
  public static final class RechargeResultReq extends
      com.google.protobuf.GeneratedMessage
      implements RechargeResultReqOrBuilder {
    // Use RechargeResultReq.newBuilder() to construct.
    private RechargeResultReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RechargeResultReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RechargeResultReq defaultInstance;
    public static RechargeResultReq getDefaultInstance() {
      return defaultInstance;
    }

    public RechargeResultReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RechargeResultReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ccapi.GlobalDef.ReqHeader.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = reqHeader_.toBuilder();
              }
              reqHeader_ = input.readMessage(ccapi.GlobalDef.ReqHeader.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(reqHeader_);
                reqHeader_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              ccapi.GlobalDef.ErrCode value = ccapi.GlobalDef.ErrCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                errCode_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              errMsg_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              cityPurchaseId_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              cccTokenAmount_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              lastBlockId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cityapi.City.internal_static_cityapi_RechargeResultReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cityapi.City.internal_static_cityapi_RechargeResultReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cityapi.City.RechargeResultReq.class, cityapi.City.RechargeResultReq.Builder.class);
    }

    public static com.google.protobuf.Parser<RechargeResultReq> PARSER =
        new com.google.protobuf.AbstractParser<RechargeResultReq>() {
      public RechargeResultReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RechargeResultReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RechargeResultReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .ccapi.ReqHeader ReqHeader = 1;
    public static final int REQHEADER_FIELD_NUMBER = 1;
    private ccapi.GlobalDef.ReqHeader reqHeader_;
    /**
     * <code>required .ccapi.ReqHeader ReqHeader = 1;</code>
     */
    public boolean hasReqHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ccapi.ReqHeader ReqHeader = 1;</code>
     */
    public ccapi.GlobalDef.ReqHeader getReqHeader() {
      return reqHeader_;
    }
    /**
     * <code>required .ccapi.ReqHeader ReqHeader = 1;</code>
     */
    public ccapi.GlobalDef.ReqHeaderOrBuilder getReqHeaderOrBuilder() {
      return reqHeader_;
    }

    // required .ccapi.ErrCode ErrCode = 2;
    public static final int ERRCODE_FIELD_NUMBER = 2;
    private ccapi.GlobalDef.ErrCode errCode_;
    /**
     * <code>required .ccapi.ErrCode ErrCode = 2;</code>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .ccapi.ErrCode ErrCode = 2;</code>
     */
    public ccapi.GlobalDef.ErrCode getErrCode() {
      return errCode_;
    }

    // required string ErrMsg = 3;
    public static final int ERRMSG_FIELD_NUMBER = 3;
    private java.lang.Object errMsg_;
    /**
     * <code>required string ErrMsg = 3;</code>
     */
    public boolean hasErrMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string ErrMsg = 3;</code>
     */
    public java.lang.String getErrMsg() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ErrMsg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string CityPurchaseId = 4;
    public static final int CITYPURCHASEID_FIELD_NUMBER = 4;
    private java.lang.Object cityPurchaseId_;
    /**
     * <code>required string CityPurchaseId = 4;</code>
     */
    public boolean hasCityPurchaseId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string CityPurchaseId = 4;</code>
     */
    public java.lang.String getCityPurchaseId() {
      java.lang.Object ref = cityPurchaseId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cityPurchaseId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string CityPurchaseId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCityPurchaseIdBytes() {
      java.lang.Object ref = cityPurchaseId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cityPurchaseId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string CccTokenAmount = 5;
    public static final int CCCTOKENAMOUNT_FIELD_NUMBER = 5;
    private java.lang.Object cccTokenAmount_;
    /**
     * <code>required string CccTokenAmount = 5;</code>
     *
     * <pre>
     *带小数点 精度4 、ddd-&gt;ccc 1：1
     * </pre>
     */
    public boolean hasCccTokenAmount() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string CccTokenAmount = 5;</code>
     *
     * <pre>
     *带小数点 精度4 、ddd-&gt;ccc 1：1
     * </pre>
     */
    public java.lang.String getCccTokenAmount() {
      java.lang.Object ref = cccTokenAmount_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cccTokenAmount_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string CccTokenAmount = 5;</code>
     *
     * <pre>
     *带小数点 精度4 、ddd-&gt;ccc 1：1
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCccTokenAmountBytes() {
      java.lang.Object ref = cccTokenAmount_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cccTokenAmount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string LastBlockId = 6;
    public static final int LASTBLOCKID_FIELD_NUMBER = 6;
    private java.lang.Object lastBlockId_;
    /**
     * <code>required string LastBlockId = 6;</code>
     */
    public boolean hasLastBlockId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string LastBlockId = 6;</code>
     */
    public java.lang.String getLastBlockId() {
      java.lang.Object ref = lastBlockId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastBlockId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string LastBlockId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getLastBlockIdBytes() {
      java.lang.Object ref = lastBlockId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastBlockId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      reqHeader_ = ccapi.GlobalDef.ReqHeader.getDefaultInstance();
      errCode_ = ccapi.GlobalDef.ErrCode.ERR_SUCCESS;
      errMsg_ = "";
      cityPurchaseId_ = "";
      cccTokenAmount_ = "";
      lastBlockId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasReqHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasErrCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasErrMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCityPurchaseId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCccTokenAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastBlockId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getReqHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, reqHeader_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, errCode_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getErrMsgBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getCityPurchaseIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getCccTokenAmountBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getLastBlockIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, reqHeader_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, errCode_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getErrMsgBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCityPurchaseIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getCccTokenAmountBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getLastBlockIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cityapi.City.RechargeResultReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cityapi.City.RechargeResultReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cityapi.City.RechargeResultReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cityapi.City.RechargeResultReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cityapi.City.RechargeResultReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cityapi.City.RechargeResultReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cityapi.City.RechargeResultReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cityapi.City.RechargeResultReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cityapi.City.RechargeResultReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cityapi.City.RechargeResultReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cityapi.City.RechargeResultReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cityapi.RechargeResultReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cityapi.City.RechargeResultReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cityapi.City.internal_static_cityapi_RechargeResultReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cityapi.City.internal_static_cityapi_RechargeResultReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cityapi.City.RechargeResultReq.class, cityapi.City.RechargeResultReq.Builder.class);
      }

      // Construct using cityapi.City.RechargeResultReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getReqHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (reqHeaderBuilder_ == null) {
          reqHeader_ = ccapi.GlobalDef.ReqHeader.getDefaultInstance();
        } else {
          reqHeaderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        errCode_ = ccapi.GlobalDef.ErrCode.ERR_SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000002);
        errMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        cityPurchaseId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        cccTokenAmount_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        lastBlockId_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cityapi.City.internal_static_cityapi_RechargeResultReq_descriptor;
      }

      public cityapi.City.RechargeResultReq getDefaultInstanceForType() {
        return cityapi.City.RechargeResultReq.getDefaultInstance();
      }

      public cityapi.City.RechargeResultReq build() {
        cityapi.City.RechargeResultReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cityapi.City.RechargeResultReq buildPartial() {
        cityapi.City.RechargeResultReq result = new cityapi.City.RechargeResultReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (reqHeaderBuilder_ == null) {
          result.reqHeader_ = reqHeader_;
        } else {
          result.reqHeader_ = reqHeaderBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errCode_ = errCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errMsg_ = errMsg_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.cityPurchaseId_ = cityPurchaseId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.cccTokenAmount_ = cccTokenAmount_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.lastBlockId_ = lastBlockId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cityapi.City.RechargeResultReq) {
          return mergeFrom((cityapi.City.RechargeResultReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cityapi.City.RechargeResultReq other) {
        if (other == cityapi.City.RechargeResultReq.getDefaultInstance()) return this;
        if (other.hasReqHeader()) {
          mergeReqHeader(other.getReqHeader());
        }
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasErrMsg()) {
          bitField0_ |= 0x00000004;
          errMsg_ = other.errMsg_;
          onChanged();
        }
        if (other.hasCityPurchaseId()) {
          bitField0_ |= 0x00000008;
          cityPurchaseId_ = other.cityPurchaseId_;
          onChanged();
        }
        if (other.hasCccTokenAmount()) {
          bitField0_ |= 0x00000010;
          cccTokenAmount_ = other.cccTokenAmount_;
          onChanged();
        }
        if (other.hasLastBlockId()) {
          bitField0_ |= 0x00000020;
          lastBlockId_ = other.lastBlockId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReqHeader()) {
          
          return false;
        }
        if (!hasErrCode()) {
          
          return false;
        }
        if (!hasErrMsg()) {
          
          return false;
        }
        if (!hasCityPurchaseId()) {
          
          return false;
        }
        if (!hasCccTokenAmount()) {
          
          return false;
        }
        if (!hasLastBlockId()) {
          
          return false;
        }
        if (!getReqHeader().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cityapi.City.RechargeResultReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cityapi.City.RechargeResultReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .ccapi.ReqHeader ReqHeader = 1;
      private ccapi.GlobalDef.ReqHeader reqHeader_ = ccapi.GlobalDef.ReqHeader.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ccapi.GlobalDef.ReqHeader, ccapi.GlobalDef.ReqHeader.Builder, ccapi.GlobalDef.ReqHeaderOrBuilder> reqHeaderBuilder_;
      /**
       * <code>required .ccapi.ReqHeader ReqHeader = 1;</code>
       */
      public boolean hasReqHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .ccapi.ReqHeader ReqHeader = 1;</code>
       */
      public ccapi.GlobalDef.ReqHeader getReqHeader() {
        if (reqHeaderBuilder_ == null) {
          return reqHeader_;
        } else {
          return reqHeaderBuilder_.getMessage();
        }
      }
      /**
       * <code>required .ccapi.ReqHeader ReqHeader = 1;</code>
       */
      public Builder setReqHeader(ccapi.GlobalDef.ReqHeader value) {
        if (reqHeaderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          reqHeader_ = value;
          onChanged();
        } else {
          reqHeaderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ccapi.ReqHeader ReqHeader = 1;</code>
       */
      public Builder setReqHeader(
          ccapi.GlobalDef.ReqHeader.Builder builderForValue) {
        if (reqHeaderBuilder_ == null) {
          reqHeader_ = builderForValue.build();
          onChanged();
        } else {
          reqHeaderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ccapi.ReqHeader ReqHeader = 1;</code>
       */
      public Builder mergeReqHeader(ccapi.GlobalDef.ReqHeader value) {
        if (reqHeaderBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              reqHeader_ != ccapi.GlobalDef.ReqHeader.getDefaultInstance()) {
            reqHeader_ =
              ccapi.GlobalDef.ReqHeader.newBuilder(reqHeader_).mergeFrom(value).buildPartial();
          } else {
            reqHeader_ = value;
          }
          onChanged();
        } else {
          reqHeaderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ccapi.ReqHeader ReqHeader = 1;</code>
       */
      public Builder clearReqHeader() {
        if (reqHeaderBuilder_ == null) {
          reqHeader_ = ccapi.GlobalDef.ReqHeader.getDefaultInstance();
          onChanged();
        } else {
          reqHeaderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .ccapi.ReqHeader ReqHeader = 1;</code>
       */
      public ccapi.GlobalDef.ReqHeader.Builder getReqHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getReqHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .ccapi.ReqHeader ReqHeader = 1;</code>
       */
      public ccapi.GlobalDef.ReqHeaderOrBuilder getReqHeaderOrBuilder() {
        if (reqHeaderBuilder_ != null) {
          return reqHeaderBuilder_.getMessageOrBuilder();
        } else {
          return reqHeader_;
        }
      }
      /**
       * <code>required .ccapi.ReqHeader ReqHeader = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ccapi.GlobalDef.ReqHeader, ccapi.GlobalDef.ReqHeader.Builder, ccapi.GlobalDef.ReqHeaderOrBuilder> 
          getReqHeaderFieldBuilder() {
        if (reqHeaderBuilder_ == null) {
          reqHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ccapi.GlobalDef.ReqHeader, ccapi.GlobalDef.ReqHeader.Builder, ccapi.GlobalDef.ReqHeaderOrBuilder>(
                  reqHeader_,
                  getParentForChildren(),
                  isClean());
          reqHeader_ = null;
        }
        return reqHeaderBuilder_;
      }

      // required .ccapi.ErrCode ErrCode = 2;
      private ccapi.GlobalDef.ErrCode errCode_ = ccapi.GlobalDef.ErrCode.ERR_SUCCESS;
      /**
       * <code>required .ccapi.ErrCode ErrCode = 2;</code>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .ccapi.ErrCode ErrCode = 2;</code>
       */
      public ccapi.GlobalDef.ErrCode getErrCode() {
        return errCode_;
      }
      /**
       * <code>required .ccapi.ErrCode ErrCode = 2;</code>
       */
      public Builder setErrCode(ccapi.GlobalDef.ErrCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .ccapi.ErrCode ErrCode = 2;</code>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errCode_ = ccapi.GlobalDef.ErrCode.ERR_SUCCESS;
        onChanged();
        return this;
      }

      // required string ErrMsg = 3;
      private java.lang.Object errMsg_ = "";
      /**
       * <code>required string ErrMsg = 3;</code>
       */
      public boolean hasErrMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string ErrMsg = 3;</code>
       */
      public java.lang.String getErrMsg() {
        java.lang.Object ref = errMsg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          errMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ErrMsg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrMsgBytes() {
        java.lang.Object ref = errMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ErrMsg = 3;</code>
       */
      public Builder setErrMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        errMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ErrMsg = 3;</code>
       */
      public Builder clearErrMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errMsg_ = getDefaultInstance().getErrMsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string ErrMsg = 3;</code>
       */
      public Builder setErrMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        errMsg_ = value;
        onChanged();
        return this;
      }

      // required string CityPurchaseId = 4;
      private java.lang.Object cityPurchaseId_ = "";
      /**
       * <code>required string CityPurchaseId = 4;</code>
       */
      public boolean hasCityPurchaseId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string CityPurchaseId = 4;</code>
       */
      public java.lang.String getCityPurchaseId() {
        java.lang.Object ref = cityPurchaseId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          cityPurchaseId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string CityPurchaseId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCityPurchaseIdBytes() {
        java.lang.Object ref = cityPurchaseId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cityPurchaseId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string CityPurchaseId = 4;</code>
       */
      public Builder setCityPurchaseId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        cityPurchaseId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string CityPurchaseId = 4;</code>
       */
      public Builder clearCityPurchaseId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        cityPurchaseId_ = getDefaultInstance().getCityPurchaseId();
        onChanged();
        return this;
      }
      /**
       * <code>required string CityPurchaseId = 4;</code>
       */
      public Builder setCityPurchaseIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        cityPurchaseId_ = value;
        onChanged();
        return this;
      }

      // required string CccTokenAmount = 5;
      private java.lang.Object cccTokenAmount_ = "";
      /**
       * <code>required string CccTokenAmount = 5;</code>
       *
       * <pre>
       *带小数点 精度4 、ddd-&gt;ccc 1：1
       * </pre>
       */
      public boolean hasCccTokenAmount() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string CccTokenAmount = 5;</code>
       *
       * <pre>
       *带小数点 精度4 、ddd-&gt;ccc 1：1
       * </pre>
       */
      public java.lang.String getCccTokenAmount() {
        java.lang.Object ref = cccTokenAmount_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          cccTokenAmount_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string CccTokenAmount = 5;</code>
       *
       * <pre>
       *带小数点 精度4 、ddd-&gt;ccc 1：1
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCccTokenAmountBytes() {
        java.lang.Object ref = cccTokenAmount_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cccTokenAmount_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string CccTokenAmount = 5;</code>
       *
       * <pre>
       *带小数点 精度4 、ddd-&gt;ccc 1：1
       * </pre>
       */
      public Builder setCccTokenAmount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        cccTokenAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string CccTokenAmount = 5;</code>
       *
       * <pre>
       *带小数点 精度4 、ddd-&gt;ccc 1：1
       * </pre>
       */
      public Builder clearCccTokenAmount() {
        bitField0_ = (bitField0_ & ~0x00000010);
        cccTokenAmount_ = getDefaultInstance().getCccTokenAmount();
        onChanged();
        return this;
      }
      /**
       * <code>required string CccTokenAmount = 5;</code>
       *
       * <pre>
       *带小数点 精度4 、ddd-&gt;ccc 1：1
       * </pre>
       */
      public Builder setCccTokenAmountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        cccTokenAmount_ = value;
        onChanged();
        return this;
      }

      // required string LastBlockId = 6;
      private java.lang.Object lastBlockId_ = "";
      /**
       * <code>required string LastBlockId = 6;</code>
       */
      public boolean hasLastBlockId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string LastBlockId = 6;</code>
       */
      public java.lang.String getLastBlockId() {
        java.lang.Object ref = lastBlockId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          lastBlockId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string LastBlockId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getLastBlockIdBytes() {
        java.lang.Object ref = lastBlockId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastBlockId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string LastBlockId = 6;</code>
       */
      public Builder setLastBlockId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        lastBlockId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string LastBlockId = 6;</code>
       */
      public Builder clearLastBlockId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        lastBlockId_ = getDefaultInstance().getLastBlockId();
        onChanged();
        return this;
      }
      /**
       * <code>required string LastBlockId = 6;</code>
       */
      public Builder setLastBlockIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        lastBlockId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cityapi.RechargeResultReq)
    }

    static {
      defaultInstance = new RechargeResultReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cityapi.RechargeResultReq)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cityapi_RechargeResultRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cityapi_RechargeResultRes_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cityapi_RechargeResultReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cityapi_RechargeResultReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ncity.proto\022\007cityapi\032\020global_def.proto\"" +
      "8\n\021RechargeResultRes\022#\n\tResHeader\030\001 \002(\0132" +
      "\020.ccapi.ResHeader\"\256\001\n\021RechargeResultReq\022" +
      "#\n\tReqHeader\030\001 \002(\0132\020.ccapi.ReqHeader\022\037\n\007" +
      "ErrCode\030\002 \002(\0162\016.ccapi.ErrCode\022\016\n\006ErrMsg\030" +
      "\003 \002(\t\022\026\n\016CityPurchaseId\030\004 \002(\t\022\026\n\016CccToke" +
      "nAmount\030\005 \002(\t\022\023\n\013LastBlockId\030\006 \002(\t2Q\n\005Ci" +
      "tyS\022H\n\016RechargeResult\022\032.cityapi.Recharge" +
      "ResultReq\032\032.cityapi.RechargeResultResB;Z" +
      "9github.com/scryinfo/citychain-s/ccapi/g",
      "rpc/go_out/cityapi"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_cityapi_RechargeResultRes_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_cityapi_RechargeResultRes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cityapi_RechargeResultRes_descriptor,
              new java.lang.String[] { "ResHeader", });
          internal_static_cityapi_RechargeResultReq_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_cityapi_RechargeResultReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cityapi_RechargeResultReq_descriptor,
              new java.lang.String[] { "ReqHeader", "ErrCode", "ErrMsg", "CityPurchaseId", "CccTokenAmount", "LastBlockId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ccapi.GlobalDef.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
